version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          build: npm run install:todomvc
      - cypress/run:
          requires:
            - cypress/install
          start: npm start
          # record: true
